apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-grm3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-grm3
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-grm3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-grm3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-grm3
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nglo-tenant/rhtap-demo-app/hacbs-test-project-grm3@sha256:a9e0e648a0aae99ad8235cb84beb4493327ca5105378c2766babc0eeae9b51b6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
